server:
  port: 0
  
info:
  foo:
    bar: toto

spring:
  datasource:
    url: jdbc:mysql://${DOCKER_IP}:3306/userdb
    username: userdb
    password: userdb-password
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddlAuto: update
      dialect: mysql
  cloud:
    stream:
      bindings:
        input: message
