server:
  port: 0

info:
  foo:
    bar: test

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddlAuto: update
      dialect: mysql
  cloud:
    stream:
      bindings:
        input: message
